Computacion/urls.py
from django.urls import path
from .views import *
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', acceso, name='acceso'),
    #------------------------------VISTA DE ENCARGADOS (LISTO)--------------------#
    path('encargados/', encargados, name='encargados'),
    path('encargados/validandoA/', views.validacionA_encargado, name='validacionA_encargado'),
    path('encargados/validandoE', views.validacionE_encargado, name='validacionE_encargado'),
    path('encargados/eliminar/<int:id>/', views.eliminar_encargado, name='eliminar_encargado'),
    #------------------------------VISTA DE PROFESORES (LISTO)--------------------#
    path('profesores/', profesores, name='profesores'),
    path('profesores/validandoA/', views.validacionA_profesor, name='validacionA_profesor'),
    path('profesores/validandoE/', views.validacionE_profesor, name='validacionE_profesor'),
    path('profesores/eliminar/<int:id>/', views.eliminar_profesor, name='eliminar_profesor'),
    #------------------------------VISTA DE ALUMNOS (LISTO)--------------------#
    path('alumnos/', alumnos, name='alumnos'),
    path('alumnos/validandoA/', views.validacionA_alumno, name='validacionA_alumno'),
    path('alumnos/validandoE', views.validacionE_alumno, name='validacionE_alumno'),
    path('alumnos/eliminar/<int:id>/', views.eliminar_alumno, name='eliminar_alumno'),
    #------------------------------VISTA DE COMPUTADORAS (LISTO)--------------------#
    path('computadoras/', computadoras, name='computadoras'),
    path('computadoras/validandoA/', views.validacionA_computadora, name='validacionA_computadora'),
    path('computadoras/validandoE/', views.validacionE_computadora, name='validacionE_computadora'),
    path('computadoras/eliminar/<int:id>/', views.eliminar_computadora, name='eliminar_computadora'),
    #------------------------------VISTA DE SESIONES DE GRUPO--------------------#
    path('sesionesgrupo/', sesiones_grupo, name='sesiones_grupo'),
    path('grupos/validandoA/', views.validacionA_grupos, name='validacionA_grupos'),
    path('grupos/validandoE/', views.validacionE_grupos, name='validacionE_grupos'),
    path('grupos/eliminar/<int:id>/', views.eliminar_grupos, name='eliminar_grupo'),
    #------------------------------VISTA DE SESIONES INDIVIDUALES--------------------#
    path('sesionesindividual/', sesiones_individual, name='sesiones_individual'),
    path('individual/validandoA/', views.validacionA_individual, name='validacionA_individual'),
    path('individual/validandoE/', views.validacionE_individual, name='validacionE_individual'),
    path('individual/eliminar/<int:id>/', views.eliminar_individual, name='eliminar_individual'),
    #------------------------------VISTA DE LABORATORIO 1--------------------#
    path('laboratoriouno/', laboratorio_uno, name='laboratorio_uno'),
    #------------------------------VISTA DE LABORATORIO 2--------------------#
    path('laboratoriodos/', laboratorio_dos, name='laboratorio_dos'),
    #------------------------------VISTA DE REPORTES--------------------#
    path('reportes/', reportes, name='reportes'),
    path('reportes/validandoA/', views.validacionA_reportes, name='validacionA_reporte'),
    path('reportes/validandoE/', views.validacionE_reportes, name='validacionE_reporte'),
    path('reportes/eliminar/<int:id>/', views.eliminar_reporte, name='eliminar_reporte'),
    #------------------------------VISTA DE AYUDA--------------------#
    path('ayuda/', ayuda, name='ayuda'),
    #------------------------------VISTA DE CERRAR SESION--------------------#
    path('cerrar-sesion/', cerrar_sesion, name='cerrar_sesion'),
    #------------------------------VISTA DE REPORTES PDF--------------------#
    path('generar-computadoras/', views.generar_computadoras, name='generar_computadoras'),
    path('generar-laboratoriouno/', views.generar_laboratoriouno, name='generar_laboratoriouno'),
    path('generar-laboratoriodos/', views.generar_laboratoriodos, name='generar_laboratoriodos'),
    path('generar-individual/<int:sesion_id>/', views.generar_individual, name='generar_individual'),
    path('generar-reporte/<int:reporte_id>/', views.generar_reporte, name='generar_reporte'),
    #------------------------------PAGINA ERRO--------------------#
    path('pagina_error/', views.pagina_error, name='pagina_error'),
]

Laboratorio/urls.py
from django.contrib import admin
from django.urls import path, include

from Computacion.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login, name='login'),
    path('conn/', conn, name='conn'),
    path('acceso/', include('Computacion.urls')),
    path('qr-reader/', qr_reader_view, name='qr_reader'),
    path('registro/', registro, name='registro'),
]

Computacion/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Carrera(models.Model):
    carrera = models.CharField(unique=True, max_length=50)

    class Meta:
        managed = False
        db_table = 'carrera'


class Computadora(models.Model):
    numero = models.IntegerField()
    estado = models.IntegerField()
    laboratorio = models.IntegerField()
    cod_monitor = models.CharField(max_length=150, blank=True, null=True)
    cod_cpu = models.CharField(max_length=150, blank=True, null=True)
    ocupada = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'computadora'


class Encargado(models.Model):
    nombre = models.CharField(max_length=50)
    apellido_p = models.CharField(max_length=40)
    apellido_m = models.CharField(max_length=40)
    hora_entrada = models.TimeField(blank=True, null=True)
    hora_salida = models.TimeField(blank=True, null=True)
    usuario = models.CharField(unique=True, max_length=25)
    contrasenia = models.CharField(max_length=50)
    estado = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'encargado'


class Estudiante(models.Model):
    nombre = models.CharField(max_length=50)
    apellido_p = models.CharField(max_length=40)
    apellido_m = models.CharField(max_length=40)
    boleta = models.CharField(unique=True, max_length=15)
    grupo = models.CharField(max_length=10, blank=True, null=True)
    qr = models.CharField(unique=True, max_length=200, blank=True, null=True)
    carrera = models.ForeignKey(Carrera, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'estudiante'


class Profesor(models.Model):
    nombre = models.CharField(max_length=50)
    apellido_p = models.CharField(max_length=40)
    apellido_m = models.CharField(max_length=40)
    boleta = models.CharField(unique=True, max_length=15)
    qr = models.CharField(unique=True, max_length=200, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'profesor'


class Reporte(models.Model):
    titulo = models.CharField(max_length=80)
    descripcion = models.CharField(max_length=200)
    hora = models.TimeField()
    fecha = models.DateField()
    seguimiento = models.CharField(max_length=200, blank=True, null=True)
    encargado = models.ForeignKey(Encargado, models.DO_NOTHING)
    computadora = models.ForeignKey(Computadora, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'reporte'


class Sesion(models.Model):
    fecha = models.DateField()
    hora_inicio = models.TimeField()
    hora_final = models.TimeField(blank=True, null=True)
    activo = models.IntegerField() 
    encargado = models.ForeignKey(Encargado, models.DO_NOTHING)
    estudiante = models.ForeignKey(Estudiante, models.DO_NOTHING)
    profesor = models.ForeignKey(Profesor, models.DO_NOTHING, blank=True, null=True)
    computadora = models.ForeignKey(Computadora, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'sesion'

Computacion/templates/v_computadoras/computadora.html
{% extends "adminlte/acceso.html" %}
{% block body %}
<br>
<!-- Ventana principal MOSTRAR computadora -->
<div class="row">
    <div class="col-md-12">
        <div class="card" style="border: none; border-radius: 10px; box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.2);">
            <div class="card-header" style="text-align: center; background-color: #6D1A42; color: #ffffff; border-top-left-radius: 10px; border-top-right-radius: 10px; padding: 15px;">
                <h3 class="card-title" style="font-size: 30px;">Lista de Computadoras</h3>
                <div class="col-sm-12 text-right">
                    <a href="{% url 'generar_computadoras' %}" class="btn btn-outline-info" target="_blank"><i class="fa fa-file-pdf"></i></a>
                </div>
            </div>
            {% for message in messages %}
                <div class="notification {% if message.tags == 'error' %}error-message{% elif message.tags == 'success' %}success-message{% endif %}">{{ message }}</div>
            {% endfor %}
            <div class="card-body" style="background-color: #ffffff; padding: 20px;">
                <table id="tablita" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Numero</th>
                            <th>Estado</th>
                            <th>Laboratorio</th>
                            <th>Codigo Monitor</th>
                            <th>Codigo CPU</th>
                            <th>Ocupada</th>
                            <th>Acciones</th> 
                        </tr>
                    </thead>
                    <tbody>
                        {% for computadora in computadoras %}
                        <tr>
                            <td>{{ computadora.numero }}</td>
                            <td>
                                {% if computadora.estado == 1 %}
                                    Activo
                                {% else %}
                                    Inactiva
                                {% endif %}
                            </td>
                            <td>{{ computadora.laboratorio }}</td>
                            <td>{% if computadora.cod_monitor %}
                                    {{ computadora.cod_monitor }}
                                {% else %}
                                    N/A
                                {% endif %}</td>
                           <td>{% if computadora.cod_cpu %}{{ computadora.cod_cpu }}{% else %}N/A{% endif %}</td>
                           <td>
                                {% if computadora.ocupada == 1 %}
                                    Ocupada
                                {% else %}
                                    Desocupada
                                {% endif %}
                            </td>
                            <td>
                                <button class="btn btn-primary btn-sm btn-editar"
                                    data-toggle="modal"
                                    data-target="#editarModal"
                                    data-id="{{ computadora.id }}"
                                    data-numero="{{ computadora.numero }}"
                                    data-estado="{{ computadora.estado }}"
                                    data-laboratorio="{{ computadora.laboratorio }}"
                                    data-cod_monitor="{{ computadora.cod_monitor }}"
                                    data-cod_cpu="{{ computadora.cod_cpu }}"
                                    data-ocupada="{{ computadora.ocupada }}"><i class="fas fa-edit"></i></button>
                                <a href="{% url 'eliminar_computadora' computadora.id %}" class="btn btn-danger btn-sm" onclick="return confirm('¿Deseas eliminar este computadora?')"><i class="fas fa-trash"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#agregarModal">
                    Agregar computadora
                </button>
            </div>
        </div>
    </div>
</div>
<!-- Ventana modal para EDITAR computadora -->
<div class="modal fade" id="editarModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modificando Computadora</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Contenido de la ventana modal aquí -->
                <form class="formAgregar" id="editarForm" method="post" action="{% url 'validacionE_computadora' %}">
                    {% csrf_token %}
                    <input type="hidden" name="id" id="id_computadora" value="">
                    <div class="form-group">
                        <label>Numero</label>
                        <input type="number" name="numero" id="id_numero" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label>Estado</label>
                        <select name="estado" id="id_estado" class="form-control" required>
                            <option value="1">Activo</option>
                            <option value="0">Inactivo</option>
                        </select>
                    </div> 
                    <div class="form-group">
                        <label>Laboratorio</label>
                        <select name="laboratorio" id="id_laboratorio" class="form-control" required>
                            <option value="1">Laboratorio 1</option>
                            <option value="2">Laboratorio 2</option>
                        </select>
                    </div> 
                    <div class="form-group">
                        <label>Codigo del Monitor</label>
                        <input type="text" name="cod_monitor" id="id_cod_monitor" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label>Codigo del CPU</label>
                        <input type="text" name="cod_cpu" id="id_cod_cpu" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label>Ocupada</label>
                        <select name="ocupada" id="id_ocupada" class="form-control" required>
                            <option value="1">Ocupada</option>
                            <option value="0">Desocupada</option>
                        </select>
                    </div>                    
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btn-editar">Editar Computadora</button>
            </div>
        </div>
    </div>
</div>
<!-- Ventana modal para AGREGAR computadora -->
<div class="modal fade" id="agregarModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Agregando Computadora</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Contenido de la ventana modal aquí -->
                <form class="formAgregar" id="agregarForm" method="post" action="{% url 'validacionA_computadora' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Numero</label>
                        <input type="number" name="numero" id="id_numero" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label>Estado</label>
                        <select name="estado" id="id_estado" class="form-control" required>
                            <option value="1">Activo</option>
                            <option value="0">Inactivo</option>
                        </select>
                    </div> 
                    <div class="form-group">
                        <label>Laboratorio</label>
                        <select name="laboratorio" id="id_laboratorio" class="form-control" required>
                            <option value="1">Laboratorio 1</option>
                            <option value="2">Laboratorio 2</option>
                        </select>
                    </div> 
                    <div class="form-group">
                        <label>Codigo del Monitor</label>
                        <input type="text" name="cod_monitor" id="id_cod_monitor" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label>Codigo del CPU</label>
                        <input type="text" name="cod_cpu" id="id_cod_cpu" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label>Ocupada</label>
                        <select name="ocupada" id="id_ocupada" class="form-control" required>
                            <option value="1">Ocupada</option>
                            <option value="0">Desocupada</option>
                        </select>
                    </div>  
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btn-guardar">Agregar Computadora</button>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        var tablaComputadoras = $('#tablita').DataTable({
            ...idioma
        });

        $('#tablita tbody').on('click', '.btn-editar', function () {
            var data = tablaComputadoras.row($(this).closest('tr')).data();
            // Obtener los datos del computadora de la fila
            var numero = $(this).data("numero");
            var estado = $(this).data("estado");
            var laboratorio = $(this).data("laboratorio");
            var cod_monitor = $(this).data("cod_monitor");
            var cod_cpu = $(this).data("cod_cpu");
            var ocupada = $(this).data("ocupada");
            var id = $(this).data("id");

            // Rellenar el formulario de la ventana modal con los datos de la computadora
            $("#editarForm #id_numero").val(numero);
            $("#editarForm #id_estado").val(estado);
            $("#editarForm #id_laboratorio").val(laboratorio);
            $("#editarForm #id_cod_monitor").val(cod_monitor);
            $("#editarForm #id_cod_cpu").val(cod_cpu);
            $("#editarForm #id_ocupada").val(ocupada);
            $("#editarForm #id_computadora").val(id);
        });
    });
    //Funcion para abrir Ventana de EDITAR
    $(document).ready(function () {
        // Captura el evento de clic en el botón "Editar computadora" y envía el formulario
        $('#btn-editar').click(function () {
            $('#editarForm').submit();
        });
    });
    //Funcion para abrir Ventana de AGREGAR
    $(document).ready(function () {
        // Captura el evento de clic en el botón "Guardar computadora" y envía el formulario
        $('#btn-guardar').click(function () {
            $('#agregarForm').submit();
        });
    });
</script>
{% endblock %}